services:
  postgres-product:
    image: postgres:15
    container_name: postgres-product
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    volumes:
      - ./product-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3001:3001"
    env_file:
      - ./product-service/.env
    depends_on:
      - postgres-product

  mysql-inventory:
    image: mysql:8
    container_name: mysql-inventory
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_db
    volumes:
      - ./inventory-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8002:8000"
    env_file:
      - ./inventory-service/.env
    depends_on:
      - mysql-inventory


  mongo-distribution:
    image: mongo:6
    container_name: mongo-distribution
    ports:
      - "27018:27017"

  distribution-service:
    build: ./distribution-service
    container_name: distribution-service
    ports:
      - "8083:8083"
    depends_on:
      - mongo-distribution
      - inventory-service

  user-service:
    build: ./user-service
    image: user-service:latest
    container_name: user-service
    ports:
      - "8001:8000"
    volumes:
      - ./user-service/database:/app/database