server:
  port: ${SERVER_PORT:8083}

spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:mongo-distribution}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:distribution_db}
  application:
    name: distribution-service

inventory:
  service:
    url: ${INVENTORY_SERVICE_URL:http://inventory-service:8000}

logging:
  level:
    org.springframework.web: INFO
    distribution: DEBUG
